// 课程数据：小吴手绘汽车（汽车设计手绘预科 · 20 课）
export const SITE_DATA = {
  siteName: "小吴手绘汽车",
  units: [
    {
      id: "unit-1",
      title: "单元一 · 比例与结构",
      lessons: [
        {
          id: 1,
          title: "汽车比例系统",
          goal: "用轮径 D 作为基准尺，精确控制车长、轴距、车高与悬垂。",
          steps: [
            { caption: "画两个轮径圆，作为比例的基准尺", art: "assets/illustrations/lesson-01-step-01.svg" },
            { caption: "定出轴距与前悬、后悬的位置", art: "assets/illustrations/lesson-01-step-02.svg" },
            { caption: "用 D 校核车长与车高：车长约 7D、车高约 2.2D", art: "assets/illustrations/lesson-01-step-03.svg" },
            { caption: "画出带轮拱的整体轮廓", art: "assets/illustrations/lesson-01-step-04.svg" },
            { caption: "标注尺寸线，校验每个比例关系", art: "assets/illustrations/lesson-01-step-05.svg" },
          ],
          tips: ["比例是设计的骨架，先定 D 再画细节", "轴距≈4.3D、前悬≈1.27D、后悬≈1.46D，画完用 D 量一遍", "同一比例可以画轿车、SUV、跑车，只是数值微调"],
        },
        {
          id: 2,
          title: "透视基础",
          goal: "理解视平线、消失点与地面投影，让车稳稳立在纸面上。",
          steps: [
            { caption: "先画视平线和地面线", art: "assets/illustrations/lesson-02-step-01.svg" },
            { caption: "画前轮与后轮的透视椭圆（前大后小）", art: "assets/illustrations/lesson-02-step-02.svg" },
            { caption: "确定轮毂圆心的透视位置", art: "assets/illustrations/lesson-02-step-03.svg" },
            { caption: "加地面投影，确认整车的姿态", art: "assets/illustrations/lesson-02-step-04.svg" },
            { caption: "用消失线检查透视是否统一", art: "assets/illustrations/lesson-02-step-05.svg" },
          ],
          tips: ["视平线越高，看到的车顶越多", "透视椭圆的长轴永远是水平的", "所有平行线要交到同一个消失点"],
        },
        {
          id: 3,
          title: "侧视造型",
          goal: "从真实轮廓出发，练习腰线、座舱与悬垂的姿态控制。",
          steps: [
            { caption: "先定轮距与轮径，再起整体轮廓", art: "assets/illustrations/lesson-03-step-01.svg" },
            { caption: "座舱位置：控制 A 柱与 C 柱的倾斜", art: "assets/illustrations/lesson-03-step-02.svg" },
            { caption: "让腰线（beltline）贯穿整个车身", art: "assets/illustrations/lesson-03-step-03.svg" },
            { caption: "调整前后悬与姿态（stance）", art: "assets/illustrations/lesson-03-step-04.svg" },
            { caption: "加轮拱与车底阴影，完成侧视", art: "assets/illustrations/lesson-03-step-05.svg" },
          ],
          tips: ["腰线是侧视的灵魂线，先轻后重", "轮拱越贴近车轮，姿态越有运动感", "A 柱倾斜决定整车的性格"],
        },
        {
          id: 4,
          title: "线稿质量控制",
          goal: "掌握握笔运笔、长线一笔过，区分结构线、造型线与分件线。",
          steps: [
            { caption: "用轻结构线定位比例", art: "assets/illustrations/lesson-04-step-01.svg" },
            { caption: "造型线：外轮廓尽量一笔画过", art: "assets/illustrations/lesson-04-step-02.svg" },
            { caption: "分件线：门缝、引擎盖、保险杠", art: "assets/illustrations/lesson-04-step-03.svg" },
            { caption: "在转折与受光处加重线", art: "assets/illustrations/lesson-04-step-04.svg" },
            { caption: "完成一张干净的侧视线稿", art: "assets/illustrations/lesson-04-step-05.svg" },
          ],
          tips: ["画长线用手臂发力，不要用手腕", "先轻后重：轻线找形，重线定型", "线稿的干净来自'少改'，不是'重画'"],
        },
      ],
    },
    {
      id: "unit-2",
      title: "单元二 · 透视与视角",
      lessons: [
        {
          id: 5,
          title: "一点透视基础",
          goal: "掌握一点透视的视平线、消失点与透视盒画法。",
          steps: [
            { caption: "画视平线与一个消失点", art: "assets/illustrations/lesson-05-step-01.svg" },
            { caption: "画一个透视盒：先定近处的大面", art: "assets/illustrations/lesson-05-step-02.svg" },
            { caption: "所有纵深线收向消失点", art: "assets/illustrations/lesson-05-step-03.svg" },
            { caption: "把车身轮廓放进透视盒", art: "assets/illustrations/lesson-05-step-04.svg" },
          ],
          tips: ["消失点放在画面内，透视会更自然", "先盒子后车身，避免比例失控"],
        },
        {
          id: 6,
          title: "轮子透视椭圆",
          goal: "画出前后轮的透视椭圆，让轮子符合地面透视。",
          steps: [
            { caption: "先画前轮的透视椭圆与十字线", art: "assets/illustrations/lesson-06-step-01.svg" },
            { caption: "画后轮椭圆：更小、更扁", art: "assets/illustrations/lesson-06-step-02.svg" },
            { caption: "连接轮心，检查轴距透视", art: "assets/illustrations/lesson-06-step-03.svg" },
            { caption: "加轮拱，让椭圆嵌进车身", art: "assets/illustrations/lesson-06-step-04.svg" },
            { caption: "画地面投影，校验椭圆角度", art: "assets/illustrations/lesson-06-step-05.svg" },
          ],
          tips: ["椭圆长轴永远水平，两端永远对称", "前后轮的大小差就是透视深度", "轮子画不好，整台车就'浮'起来"],
        },
        {
          id: 7,
          title: "3/4 前视角",
          goal: "掌握设计稿最常用的 3/4 前视角：前脸与侧面同时可见。",
          steps: [
            { caption: "画透视盒：视平线与消失方向", art: "assets/illustrations/lesson-07-step-01.svg" },
            { caption: "前脸梯形与侧面的透视关系", art: "assets/illustrations/lesson-07-step-02.svg" },
            { caption: "轮子透视椭圆与轮拱", art: "assets/illustrations/lesson-07-step-03.svg" },
            { caption: "灯组与前脸曲面", art: "assets/illustrations/lesson-07-step-04.svg" },
            { caption: "完成 3/4 前视角线稿", art: "assets/illustrations/lesson-07-step-05.svg" },
          ],
          tips: ["3/4 视角同时看到前脸和侧面两个面", "轮子椭圆长轴的角度决定透视强度", "先画轮子再画车身，最不容易翻车"],
        },
        {
          id: 8,
          title: "3/4 后视角",
          goal: "掌握 3/4 后视角：尾灯、尾部曲面与对称关系。",
          steps: [
            { caption: "画尾部透视盒与地面线", art: "assets/illustrations/lesson-08-step-01.svg" },
            { caption: "后窗与 C 柱的倾斜", art: "assets/illustrations/lesson-08-step-02.svg" },
            { caption: "贯穿式尾灯与牌照区", art: "assets/illustrations/lesson-08-step-03.svg" },
            { caption: "尾部曲面与扩散器", art: "assets/illustrations/lesson-08-step-04.svg" },
            { caption: "完成 3/4 后视角线稿", art: "assets/illustrations/lesson-08-step-05.svg" },
          ],
          tips: ["车尾是对称的：左右灯、左右轮要呼应", "尾部曲面用明暗表达，不要用多余的线"],
        },
      ],
    },
    {
      id: "unit-3",
      title: "单元三 · 新能源设计语言",
      lessons: [
        {
          id: 9,
          title: "前脸与封闭式格栅",
          goal: "理解 EV 前脸设计语言：封闭格栅、曲面与分件线。",
          steps: [
            { caption: "观察真实 EV 前脸的封闭式处理", art: "assets/illustrations/lesson-09-step-01.svg" },
            { caption: "画前脸曲面与下保险杠的分件", art: "assets/illustrations/lesson-09-step-02.svg" },
            { caption: "用连续长线表现干净的曲面", art: "assets/illustrations/lesson-09-step-03.svg" },
            { caption: "对比油车格栅与电车封闭前脸", art: "assets/illustrations/lesson-09-step-04.svg" },
            { caption: "标注分件线走向，检查曲面连续性", art: "assets/illustrations/lesson-09-step-05.svg" },
          ],
          tips: ["没有格栅意味着元素更少，曲面必须更准确", "分件线要顺着曲面走势画", "前脸的'表情'由灯组与进气口决定"],
        },
        {
          id: 10,
          title: "灯光设计",
          goal: "画出贯穿式灯带与日行灯，理解灯具与品牌语言的关系。",
          steps: [
            { caption: "定位灯带：一条贯穿前脸的横线", art: "assets/illustrations/lesson-10-step-01.svg" },
            { caption: "画出灯组上扬的'眼神'", art: "assets/illustrations/lesson-10-step-02.svg" },
            { caption: "表现灯腔的高光与层次", art: "assets/illustrations/lesson-10-step-03.svg" },
            { caption: "用留白强调发光感", art: "assets/illustrations/lesson-10-step-04.svg" },
            { caption: "对比不同灯形，找品牌识别点", art: "assets/illustrations/lesson-10-step-05.svg" },
          ],
          tips: ["灯带是新能源车的品牌签名", "高光靠留白表现，不要涂白", "灯形越简洁越耐看"],
        },
        {
          id: 11,
          title: "轮毂与细节",
          goal: "设计轮毂：辐条布局、轮拱关系与细节层级。",
          steps: [
            { caption: "先定轮毂圆与轮拱的间距", art: "assets/illustrations/lesson-11-step-01.svg" },
            { caption: "画辐条布局（奇数辐更显运动）", art: "assets/illustrations/lesson-11-step-02.svg" },
            { caption: "表现轮拱阴影与轮胎侧壁", art: "assets/illustrations/lesson-11-step-03.svg" },
            { caption: "加门缝、后视镜等二级细节", art: "assets/illustrations/lesson-11-step-04.svg" },
            { caption: "检查细节层级：先大形，后细节", art: "assets/illustrations/lesson-11-step-05.svg" },
          ],
          tips: ["细节要有主次：第一眼先看到整体比例", "辐条从轮毂中心放射，注意透视", "轮毂是侧面图的'眼睛'，值得单独练"],
        },
        {
          id: 12,
          title: "草图迭代",
          goal: "用五分钟快稿，在同一比例下画出多个方案。",
          steps: [
            { caption: "固定比例基准：D 圆与轴距", art: "assets/illustrations/lesson-12-step-01.svg" },
            { caption: "快速画两三个不同姿态的方案", art: "assets/illustrations/lesson-12-step-02.svg" },
            { caption: "对比方案，圈出最强的一个", art: "assets/illustrations/lesson-12-step-03.svg" },
            { caption: "在选中方案上加设计细节", art: "assets/illustrations/lesson-12-step-04.svg" },
          ],
          tips: ["快稿不追求干净，追求数量与想法", "先求差异，再求完善", "同一比例下的方案对比才有意义"],
        },
      ],
    },
    {
      id: "unit-4",
      title: "单元四 · 渲染与表现",
      lessons: [
        {
          id: 13,
          title: "马克笔渲染基础",
          goal: "掌握平涂、渐变、叠色与高光留白四种基本技法。",
          steps: [
            { caption: "平涂：均匀快速地铺色", art: "assets/illustrations/lesson-13-step-01.svg" },
            { caption: "渐变：从深到浅过渡", art: "assets/illustrations/lesson-13-step-02.svg" },
            { caption: "叠色：建立阴影层次", art: "assets/illustrations/lesson-13-step-03.svg" },
            { caption: "高光留白与局部提亮", art: "assets/illustrations/lesson-13-step-04.svg" },
            { caption: "修正边缘，控制叠色次数", art: "assets/illustrations/lesson-13-step-05.svg" },
          ],
          tips: ["马克笔要快速扫过，不要来回涂", "先浅后深，控制叠色次数", "留白比涂白更有'光感'"],
        },
        {
          id: 14,
          title: "光影与材质",
          goal: "表现车身反光、玻璃与轮胎的材质差异。",
          steps: [
            { caption: "车身：上明下暗的柱面反光", art: "assets/illustrations/lesson-14-step-01.svg" },
            { caption: "玻璃：斜向的反射带", art: "assets/illustrations/lesson-14-step-02.svg" },
            { caption: "轮胎：哑光深色加一条高光弧", art: "assets/illustrations/lesson-14-step-03.svg" },
            { caption: "地面接触阴影定住整车", art: "assets/illustrations/lesson-14-step-04.svg" },
            { caption: "整体明暗检查：光源方向统一", art: "assets/illustrations/lesson-14-step-05.svg" },
          ],
          tips: ["玻璃与车身的反光方向要保持一致", "哑光与亮面靠明度差区分", "所有阴影都要服从同一个光源"],
        },
        {
          id: 15,
          title: "快速表现图",
          goal: "用天空、地面与速度线快速营造氛围感。",
          steps: [
            { caption: "画天空色带与地平线", art: "assets/illustrations/lesson-15-step-01.svg" },
            { caption: "车身快速铺大色", art: "assets/illustrations/lesson-15-step-02.svg" },
            { caption: "画地面反射与接触阴影", art: "assets/illustrations/lesson-15-step-03.svg" },
            { caption: "加速度线与光效，完成表现图", art: "assets/illustrations/lesson-15-step-04.svg" },
          ],
          tips: ["表现图先铺背景再画车，节奏更快", "速度线别画满，留白更有动感"],
        },
        {
          id: 16,
          title: "完整效果图",
          goal: "完成一张包含多角度插画与版式的完整效果图。",
          steps: [
            { caption: "主图：侧视完成稿铺色", art: "assets/illustrations/lesson-16-step-01.svg" },
            { caption: "小插画：轮毂细节研究", art: "assets/illustrations/lesson-16-step-02.svg" },
            { caption: "小插画：前脸与灯组", art: "assets/illustrations/lesson-16-step-03.svg" },
            { caption: "加标题块与设计说明", art: "assets/illustrations/lesson-16-step-04.svg" },
            { caption: "统一版式，检查主次关系", art: "assets/illustrations/lesson-16-step-05.svg" },
          ],
          tips: ["效果图是一张'海报'，主图占最大面积", "小插画要与主图风格一致", "标题字要少，设计说明要短"],
        },
      ],
    },
    {
      id: "unit-5",
      title: "单元五 · 创作与作品集",
      lessons: [
        {
          id: 17,
          title: "概念车创作",
          goal: "完成一个完整流程：灵感→比例→造型→渲染→命名。",
          steps: [
            { caption: "定主题与灵感方向", art: "assets/illustrations/lesson-17-step-01.svg" },
            { caption: "用 D 圆定比例，画两三个方案", art: "assets/illustrations/lesson-17-step-02.svg" },
            { caption: "定稿造型与关键线条", art: "assets/illustrations/lesson-17-step-03.svg" },
            { caption: "渲染光影与材质", art: "assets/illustrations/lesson-17-step-04.svg" },
            { caption: "加背景、写车名与设计说明", art: "assets/illustrations/lesson-17-step-05.svg" },
          ],
          tips: ["设计说明写三句话：灵感、比例、目标用户", "命名要短，有画面感", "概念车允许夸张，但比例不能破"],
        },
        {
          id: 18,
          title: "家族化设计",
          goal: "用同一品牌语言设计两到三款不同定位的车。",
          steps: [
            { caption: "确定家族设计语言：灯形、格栅、腰线", art: "assets/illustrations/lesson-18-step-01.svg" },
            { caption: "画第一款：轿车定位", art: "assets/illustrations/lesson-18-step-02.svg" },
            { caption: "画第二款：SUV 定位（同语言不同比例）", art: "assets/illustrations/lesson-18-step-03.svg" },
            { caption: "对比两款，检查语言一致性", art: "assets/illustrations/lesson-18-step-04.svg" },
          ],
          tips: ["家族设计=相同的'脸'，不同的'身'", "比例变了，语言不变，才能一眼认出"],
        },
        {
          id: 19,
          title: "作品集排版",
          goal: "把多张设计稿排成一页，学会写标题、标注与说明。",
          steps: [
            { caption: "确定页面版式与主次", art: "assets/illustrations/lesson-19-step-01.svg" },
            { caption: "放主图与细节图，统一比例", art: "assets/illustrations/lesson-19-step-02.svg" },
            { caption: "加标题、标注线与小字说明", art: "assets/illustrations/lesson-19-step-03.svg" },
            { caption: "整体检查：留白、对齐、字体统一", art: "assets/illustrations/lesson-19-step-04.svg" },
          ],
          tips: ["一页只讲一个项目", "对齐是排版的生命线", "说明文字控制在三行以内"],
        },
        {
          id: 20,
          title: "学习总结与自评",
          goal: "对照清单自评 20 课成果，制定下一步训练计划。",
          steps: [
            { caption: "回看自己的所有草图，挑出最好的三张", art: "assets/illustrations/lesson-20-step-01.svg" },
            { caption: "用比例清单检查每张图", art: "assets/illustrations/lesson-20-step-02.svg" },
            { caption: "用透视清单检查视角", art: "assets/illustrations/lesson-20-step-03.svg" },
            { caption: "用渲染清单检查明暗", art: "assets/illustrations/lesson-20-step-04.svg" },
            { caption: "写下三条最该练的，进入下一轮", art: "assets/illustrations/lesson-20-step-05.svg" },
          ],
          tips: ["自评清单：比例、透视、线稿、渲染各 3 条", "每轮只练三件事，练透再换", "把最好的三张贴出来，下轮超越它"],
        },
      ],
    },
  ],
};
